# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        yarn
        yarn lint
        yarn build
        yarn test:e2e --headless
    #- name: Upload Codecov
    #  run: bash <(curl -s https://codecov.io/bash)
    #  if: ${{ matrix.node-version == '14.x' }}
    - uses: actions/upload-artifact@v2
      with:
        name: recordings-e2e
        path: tests/e2e/videos/
        retention-days: 14
    - name: Deploy
      if: ${{ github.event.name == 'push' && matrix.node-version == '14.x' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

