name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn --frozen-lockfile
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
    - name: Unit Test
      run: yarn test:unit -ci
    - name: Test
      run: yarn test:e2e --headless
    - uses: codecov/codecov-action@v5
      if: ${{ matrix.node-version == '22.x' }}
    - uses: actions/upload-artifact@v4
      with:
        name: recordings-e2e-${{ matrix.node-version }}
        path: tests/e2e/videos/
        retention-days: 7
    - name: Deploy
      if: ${{ github.event_name == 'push' && matrix.node-version == '22.x' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

